title: <p align="center"> Vikash Kumar </p>
logo: /assets/img/Pic.jpeg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/vikash-kumar-0a91bb120/">LinkedIn</a> |
  <a href="https://github.com/singhvikash047">GitHub</a>

  <br>
  I am working on Data Science and Machine learning related problems.
  Worked with Wipro Ltd at Engineering Design Services team.
  <br>
  </p>



theme: jekyll-theme-minimal
